name: CMake Build with LCG on CVMFS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_101/x86_64-ubuntu2004-gcc9-opt",
              "LCG_99/x86_64-ubuntu2004-gcc9-opt"]
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3.1
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
    - uses: aidasoft/run-lcg-view@v4
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          cmake -B ${{github.workspace}}/build
          cmake --build ${{github.workspace}}/build
